export { default as illustration } from './img/favorites/Illustration.png'
export { default as samsung} from './img/samsung.png'
export { default as xiaomi} from './img/xiaomi.png'
export { default as location} from './svg/location.svg'
export { default as number} from './svg/number.svg'
export { default as apple} from './svg/card/brand.svg'
export { default as rating} from './svg/card/rating.svg'
export { default as instagram} from './svg/footer/instagram.svg'
export { default as language} from './svg/footer/language.svg'
export { default as telegram} from './svg/footer/telegram.svg'
export { default as whatsapp} from './svg/footer/whatsapp.svg'
export { default as wk} from './svg/footer/wk.svg'
export { default as bin} from './svg/header/bin.svg'
export { default as favorites} from './svg/header/favorites.svg'
export { default as logo} from './svg/header/logo.svg'
export { default as phone} from './svg/header/phone.svg'
export { default as abrand} from './img/slider/apple-brand.webp'
export { default as sbrand} from './img/slider/samsung-brand.png'
export { default as xbrand} from './img/slider/xiaomi-brand.jpg'
export { default as servis} from './svg/manu-servis.svg'
export { default as contact} from './svg/contacts.svg'
export { default as cardimg} from './img/card-img.png'
export { default as inner } from './img/inner-image.png'
export { default as whatsap} from './svg/card/whatsapp 2.svg'
export { default as bin2} from './svg/card/bin.svg'
export { default as apple2} from './img/apple-phone.png'
export { default as apple3} from './img/apple-phone2.png'
export { default as delet} from './svg/card/delete.svg'
export { default as plus }  from './svg/card/plus.svg'
export { default as minus}  from './svg/card/minus.svg'
